v2006 successfull build

diff --git a/scripts/install/openfoam b/scripts/install/openfoam
--- a/scripts/install/openfoam
+++ b/scripts/install/openfoam
@@ -1,138 +1,181 @@
 #!/bin/bash -xe
 
-export WM_NCOMPPROCS=$(grep -c ^processor /proc/cpuinfo)
-
-#
-export ADIOS2_VERSION_MAJOR=2
-export ADIOS2_VERSION_MINOR=4
-export ADIOS2_VERSION_SUFFIX=0
-export ADIOS2_VERSION="${ADIOS2_VERSION_MAJOR}.${ADIOS2_VERSION_MINOR}.${ADIOS2_VERSION_SUFFIX}"
-export FFTW_VERSION=3.3.8
-export PETSC_VERSION=3.13.2
-export SCOTCH_VERSION=6.0.9
-export KAHIP_VERSION=2.12
-
-echo "export ADIOS2_VERSION=${ADIOS2_VERSION}" >> /etc/profile.d/buildenv.sh
-echo "export ADIOS2_VERSION_MAJOR=${ADIOS2_VERSION_MAJOR}" >> /etc/profile.d/buildenv.sh
-echo "export ADIOS2_VERSION_MINOR=${ADIOS2_VERSION_MINOR}" >> /etc/profile.d/buildenv.sh
-echo "export ADIOS2_VERSION_SUFFIX=${ADIOS2_VERSION_SUFFIX}" >> /etc/profile.d/buildenv.sh
-echo "export FFTW_VERSION=${FFTW_VERSION}" >> /etc/profile.d/buildenv.sh
-echo "export PETSC_VERSION=${PETSC_VERSION}" >> /etc/profile.d/buildenv.sh
-echo "export SCOTCH_VERSION=${SCOTCH_VERSION}" >> /etc/profile.d/buildenv.sh
-echo "export KAHIP_VERSION=${KAHIP_VERSION}" >> /etc/profile.d/buildenv.sh
-
 # ------------------------------------------------------------------------------
 #
-export OPENFOAM_DIR="/opt/openfoam"
-export OPENFOAM_THIRDPARTY_DIR="$OPENFOAM_DIR/ThirdParty"
+# OpenFOAM - src
+
+export WM_NCOMPPROCS=$(grep -c ^processor /proc/cpuinfo)
+
+export OPENFOAM_DIR="/opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION_ENTIRE}"
+export OPENFOAM_THIRDPARTY_DIR="/opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION_ENTIRE}"
 
 echo "export OPENFOAM_DIR=${OPENFOAM_DIR}" >> /etc/profile.d/buildenv.sh
 echo "export OPENFOAM_THIRDPARTY_DIR=${OPENFOAM_THIRDPARTY_DIR}" >> /etc/profile.d/buildenv.sh
+echo ". $OPENFOAM_DIR/etc/bashrc || echo 'warning: skip errors as long as cgal is supported by github'" >> /etc/profile.d/openfoam.sh
 
-# ------------------------------------------------------------------------------
 #
-export ADIOS2_GIT_URL="https://github.com/ornladios/ADIOS2.git"
-export ADIOS2_GIT_BRANCH="release_${ADIOS2_VERSION_MAJOR}${ADIOS2_VERSION_MINOR}"
-export ADIOS2_DIR="${OPENFOAM_THIRDPARTY_DIR}/ADIOS2-${ADIOS2_VERSION}"
-
-echo "export ADIOS2_GIT_URL=${ADIOS2_GIT_URL}" >> /etc/profile.d/buildenv.
-echo "export ADIOS2_GIT_BRANCH=${ADIOS2_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
-echo "export ADIOS2_DIR=${ADIOS2_DIR}" >> /etc/profile.d/buildenv.sh
-
-#export FFTW_GIT_URL="0"
-#export FFTW_GIT_BRANCH="0"
-#export FFTW_DIR="${OPENFOAM_THIRDPARTY_DIR}/fftw-${FFTW_VERSION}"
-
-export PETSC_GIT_URL="https://gitlab.com/petsc/petsc.git"
-export PETSC_GIT_BRANCH="v${PETSC_VERSION}"
-#export PETSC_DIR="${OPENFOAM_THIRDPARTY_DIR}/petsc_${PETSC_VERSION}"
-#export PETSC_ARCH=linux-gnu
-
-echo "export PETSC_GIT_URL=${PETSC_GIT_URL}" >> /etc/profile.d/buildenv.
-echo "export PETSC_GIT_BRANCH=${PETSC_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
-
-export SCOTCH_GIT_URL="https://gitlab.inria.fr/scotch/scotch.git"
-export SCOTCH_GIT_BRANCH="v${SCOTCH_VERSION}"
-export SCOTCH_DIR="${OPENFOAM_THIRDPARTY_DIR}/scotch_${SCOTCH_VERSION}"
-
-echo "export SCOTCH_GIT_URL=${SCOTCH_GIT_URL}" >> /etc/profile.d/buildenv.
-echo "export SCOTCH_GIT_BRANCH=${SCOTCH_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
-echo "export SCOTCH_DIR=${SCOTCH_DIR}" >> /etc/profile.d/buildenv.sh
-
-export KAHIP_GIT_URL="https://github.com/KaHIP/KaHIP.git"
-export KAHIP_GIT_BRANCH="v${KAHIP_VERSION}"
-export KAHIP_DIR="${OPENFOAM_THIRDPARTY_DIR}/kahip-${KAHIP_VERSION}"
-
-echo "export KAHIP_GIT_URL=${KAHIP_GIT_URL}" >> /etc/profile.d/buildenv.
-echo "export KAHIP_GIT_BRANCH=${KAHIP_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
-echo "export KAHIP_DIR=${KAHIP_DIR}" >> /etc/profile.d/buildenv.sh
-
-# ------------------------------------------------------------------------------
-# load sources
 git clone --branch $OPENFOAM_GIT_BRANCH            $OPENFOAM_GIT_URL            $OPENFOAM_DIR
 git clone --branch $OPENFOAM_THIRDPARTY_GIT_BRANCH $OPENFOAM_THIRDPARTY_GIT_URL $OPENFOAM_THIRDPARTY_DIR
 
 cd $OPENFOAM_DIR
 git submodule init
 
-echo ". $OPENFOAM_DIR/etc/bashrc" >> /etc/profile.d/openfoam.sh
-
-#
-git clone --branch ${ADIOS2_GIT_BRANCH} ${ADIOS2_GIT_URL} ${ADIOS2_DIR}
-git clone --branch ${SCOTCH_GIT_BRANCH} ${SCOTCH_GIT_URL} ${SCOTCH_DIR}
-#git clone --branch ${PETSC_GIT_BRANCH}  ${PETSC_GIT_URL}  ${PETSC_DIR}
-
-# KaHIP
-git clone --branch ${KAHIP_GIT_BRANCH} ${KAHIP_GIT_URL} ${KAHIP_DIR}
-
-# put petsc to third party
-#cd ${OPENFOAM_THIRDPARTY_DIR}
-#wget -q http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-${PETSC_VERSION}.tar.gz
-#tar -xzvf petsc-lite-${PETSC_VERSION}.tar.gz
-#rm -f petsc-lite-${PETSC_VERSION}.tar.gz
-
-#echo "export PETSC_DIR=${PETSC_DIR}" >> /etc/profile.d/PETSc.sh
-#echo "export PETSC_ARCH=${PETSC_ARCH}" >> /etc/profile.d/PETSc.sh
-#chmod +x /etc/profile.d/PETSc.sh
-#
-#cd ${PETSC_DIR}
-#python setup.py install
-
-# put fftw to third party
-#cd ${OPENFOAM_THIRDPARTY_DIR}
-#wget -q http://www.fftw.org/${FFTW_DIR}.tar.gz
-#tar -xzvf ${FFTW_DIR}.tar.gz
-#rm -f ${FFTW_DIR}.tar.gz
-
-# ------------------------------------------------------------------------------
-# build openfoam
-
 # ensure label size of 64 bit
 #sed -ie  's|WM_LABEL_SIZE=32|WM_LABEL_SIZE=64|' ${OPENFOAM_DIR}/etc/bashrc
 
-# config env
-. /etc/profile.d/openfoam.sh || echo "skip errors."
+# ------------------------------------------------------------------------------
+#
+# ADIOS2
+source $OPENFOAM_DIR/etc/config.sh/adios2
+
+export ADIOS2_VERSION_ENTIRE=$(echo "$adios2_version" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+export ADIOS2_VERSION_MAJOR=$(echo "$ADIOS2_VERSION_ENTIRE" | cut -d'.' -f1)
+export ADIOS2_VERSION_MINOR=$(echo "$ADIOS2_VERSION_ENTIRE" | cut -d'.' -f2)
+export ADIOS2_VERSION_SUFFIX=$(echo "$ADIOS2_VERSION_ENTIRE" | cut -d'.' -f3)
+export ADIOS2_VERSION="${ADIOS2_VERSION_MAJOR}.${ADIOS2_VERSION_MINOR}.${ADIOS2_VERSION_SUFFIX}"
+
+export ADIOS2_GIT_URL="https://github.com/ornladios/ADIOS2.git"
+export ADIOS2_GIT_BRANCH="release_${ADIOS2_VERSION_MAJOR}${ADIOS2_VERSION_MINOR}"
+export ADIOS2_DIR="${OPENFOAM_THIRDPARTY_DIR}/ADIOS2-${ADIOS2_VERSION}"
+
+echo "export ADIOS2_VERSION_ENTIRE=${ADIOS2_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_VERSION_MAJOR=${ADIOS2_VERSION_MAJOR}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_VERSION_MINOR=${ADIOS2_VERSION_MINOR}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_VERSION_SUFFIX=${ADIOS2_VERSION_SUFFIX}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_VERSION=${ADIOS2_VERSION}" >> /etc/profile.d/buildenv.sh
+
+echo "export ADIOS2_GIT_URL=${ADIOS2_GIT_URL}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_GIT_BRANCH=${ADIOS2_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
+echo "export ADIOS2_DIR=${ADIOS2_DIR}" >> /etc/profile.d/buildenv.sh
+
+git clone --branch ${ADIOS2_GIT_BRANCH} ${ADIOS2_GIT_URL} ${ADIOS2_DIR}
+
+# ------------------------------------------------------------------------------
+#
+# FFTW
+source $OPENFOAM_DIR/etc/config.sh/FFTW
+
+export FFTW_VERSION_ENTIRE=$(echo "$fftw_version" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+export FFTW_FILE_NAME="fftw-${FFTW_VERSION_ENTIRE}"
+
+echo "export FFTW_VERSION_ENTIRE=${FFTW_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export FFTW_FILE_NAME=${FFTW_FILE_NAME}" >> /etc/profile.d/buildenv.sh
+
+cd ${OPENFOAM_THIRDPARTY_DIR}
+wget -q http://www.fftw.org/${FFTW_FILE_NAME}.tar.gz
+tar -xzvf ${FFTW_FILE_NAME}.tar.gz
+rm -f ${FFTW_FILE_NAME}.tar.gz
+
+# ------------------------------------------------------------------------------
+#
+# petsc
+source $OPENFOAM_DIR/etc/config.sh/petsc
+
+export PETSC_VERSION_ENTIRE=$(echo "$petsc_version" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+export PETSC_GIT_URL="https://gitlab.com/petsc/petsc.git"
+export PETSC_GIT_BRANCH="v${PETSC_VERSION_ENTIRE}"
+export PETSC_DIR="${OPENFOAM_THIRDPARTY_DIR}/petsc_${PETSC_VERSION_ENTIRE}"
+export PETSC_ARCH=linux-gnu
+
+echo "export PETSC_VERSION_ENTIRE=${PETSC_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export PETSC_GIT_URL=${PETSC_GIT_URL}" >> /etc/profile.d/buildenv.sh
+echo "export PETSC_GIT_BRANCH=${PETSC_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
+echo "export PETSC_DIR=${PETSC_DIR}" >> /etc/profile.d/buildenv.sh
+echo "export PETSC_ARCH=${PETSC_ARCH}" >> /etc/profile.d/buildenv.sh
+
+#git clone --branch ${PETSC_GIT_BRANCH}  ${PETSC_GIT_URL}  ${PETSC_DIR}
+
+# ------------------------------------------------------------------------------
+#
+# scotch
+source $OPENFOAM_DIR/etc/config.sh/scotch
+
+export SCOTCH_VERSION_ENTIRE=$(echo "$SCOTCH_VERSION" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+export SCOTCH_GIT_URL="https://gitlab.inria.fr/scotch/scotch.git"
+export SCOTCH_GIT_BRANCH="v${SCOTCH_VERSION_ENTIRE}"
+export SCOTCH_DIR="${OPENFOAM_THIRDPARTY_DIR}/scotch_${SCOTCH_VERSION_ENTIRE}"
+
+echo "export SCOTCH_VERSION_ENTIRE=${SCOTCH_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export SCOTCH_GIT_URL=${SCOTCH_GIT_URL}" >> /etc/profile.d/buildenv.sh
+echo "export SCOTCH_GIT_BRANCH=${SCOTCH_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
+echo "export SCOTCH_DIR=${SCOTCH_DIR}" >> /etc/profile.d/buildenv.sh
+
+git clone --branch ${SCOTCH_GIT_BRANCH} ${SCOTCH_GIT_URL} ${SCOTCH_DIR}
+
+# ------------------------------------------------------------------------------
+#
+# kahip
+source $OPENFOAM_DIR/etc/config.sh/kahip
+
+export KAHIP_VERSION_ENTIRE=$(echo "$KAHIP_VERSION" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+export KAHIP_GIT_URL="https://github.com/KaHIP/KaHIP.git"
+export KAHIP_GIT_BRANCH="v${KAHIP_VERSION_ENTIRE}"
+export KAHIP_DIR="${OPENFOAM_THIRDPARTY_DIR}/kahip-${KAHIP_VERSION_ENTIRE}"
+
+echo "export KAHIP_VERSION_ENTIRE=${KAHIP_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export KAHIP_GIT_URL=${KAHIP_GIT_URL}" >> /etc/profile.d/buildenv.sh
+echo "export KAHIP_GIT_BRANCH=${KAHIP_GIT_BRANCH}" >> /etc/profile.d/buildenv.sh
+echo "export KAHIP_DIR=${KAHIP_DIR}" >> /etc/profile.d/buildenv.sh
+
+git clone --branch ${KAHIP_GIT_BRANCH} ${KAHIP_GIT_URL} ${KAHIP_DIR}
+
+# ------------------------------------------------------------------------------
+#
+# CGAL
+#source $OPENFOAM_DIR/etc/config.sh/CGAL
+#boost_version=boost_1_66_0
+#cgal_version=CGAL-4.12.2
+
+export BOOST_VERSION_ENTIRE=$(echo "$boost_version" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||' | sed -r 's/[_-]+/./g')
+export CGAL_VERSION_ENTIRE=$(echo "$cgal_version" | sed 's|^[^-_]*||' | sed 's|^-||' | sed 's|^_||')
+
+export BOOST_ARCHIVE_FILE_NAME="boost_$(echo $BOOST_VERSION_ENTIRE  | sed -r 's/[.-]+/_/g').tar.gz"
+export CGAL_ARCHIVE_FILE_NAME="v${CGAL_VERSION_ENTIRE}.tar.gz"
+
+export BOOST_DOWNLOAD_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION_ENTIRE}/source/${BOOST_ARCHIVE_FILE_NAME}"
+export CGAL_DOWNLOAD_URL="https://github.com/CGAL/cgal/archive/${CGAL_ARCHIVE_FILE_NAME}"
+
+echo "export BOOST_VERSION_ENTIRE=${BOOST_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export CGAL_VERSION_ENTIRE=${CGAL_VERSION_ENTIRE}" >> /etc/profile.d/buildenv.sh
+echo "export BOOST_ARCHIVE_FILE_NAME=${BOOST_ARCHIVE_FILE_NAME}" >> /etc/profile.d/buildenv.sh
+echo "export CGAL_ARCHIVE_FILE_NAME=${CGAL_ARCHIVE_FILE_NAME}" >> /etc/profile.d/buildenv.sh
+echo "export BOOST_DOWNLOAD_URL=${BOOST_DOWNLOAD_URL}" >> /etc/profile.d/buildenv.sh
+echo "export CGAL_DOWNLOAD_URL=${CGAL_DOWNLOAD_URL}" >> /etc/profile.d/buildenv.sh
+
+#cd $OPENFOAM_THIRDPARTY_DIR
+
+#wget -q ${BOOST_DOWNLOAD_URL}
+#tar -xzvf ${BOOST_ARCHIVE_FILE_NAME}
+#rm -f ${BOOST_ARCHIVE_FILE_NAME}
+
+#wget -q ${CGAL_DOWNLOAD_URL}
+#tar -xzvf ${CGAL_ARCHIVE_FILE_NAME}
+#rm -f ${CGAL_ARCHIVE_FILE_NAME}
+
+# ------------------------------------------------------------------------------
+#
+# OpenFOAM - build
+
+. /etc/profile.d/openfoam.sh
 
 #
 cd ${OPENFOAM_THIRDPARTY_DIR}
+./makeFFTW
+./makeSCOTCH
 ./makeAdios2
 ./makeKAHIP
+./Allwmake
 #./makePETSC
-./makeSCOTCH
-#./makeFFTW
 
 #
 cd ${OPENFOAM_DIR}
-./Allwmake -j -s -q -a
+./Allwmake -j
 
-# ------------------------------------------------------------------------------
 # cleanup openfoam
-
 cd ${OPENFOAM_THIRDPARTY_DIR}
 ./Allclean
 
 cd ${OPENFOAM_DIR}
-#./Allclean
 find -name '*.o' | xargs rm
 find -name '*.dep' | xargs rm
 #rm -rf build/*
